[package]
name = "test-ringbuf"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-utils = "0.8.20"
ringbuf = "0.4.7"

[dev-dependences]
criterion = "0.5"

[[bench]]
name = "ringbuf_reference"
harness = false

